// 領域 2：網路、HTTP 與 API 設計
// 技能內文（points / checklist / refs）在 ./body/d2-web.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'web',
  no: 2,
  title: '網路、HTTP 與 API 設計',
  en: 'HTTP & API DESIGN',
  color: 'aqua',
  tagline: 'HTTP 的另一端：由你決定狀態碼、標頭與資源長什麼樣。',
  desc: 'API 是後端對外的合約。這一區把 HTTP 從「fetch 就好」拆成看得見的步驟，再學怎麼設計別人用起來不會罵的 REST API：資源、方法、狀態碼、分頁、錯誤格式、版本。',
  skills: [
    {
      id: 'http-basics',
      title: '一個 HTTP 請求的一生',
      en: 'HTTP fundamentals',
      level: 1,
      summary: 'DNS → TCP → TLS → 請求 → 伺服器 → 回應 → 快取，每一步都可能是延遲或 bug 的來源。',
      example: { primary: 'HTTP/1.1 + HTTP/2', alts: ['HTTP/3 (QUIC)'] },
      keywords: [],
      lab: 'HttpLab',
    },
    {
      id: 'rest-design',
      title: 'REST API 設計',
      en: 'REST design',
      level: 1,
      summary: '資源是名詞、方法是動詞、狀態碼是結果——把這三件事對齊，API 就好用。',
      example: { primary: 'REST over JSON', alts: ['GraphQL', 'gRPC'] },
      keywords: [],
      lab: 'RestLab',
    },
    {
      id: 'api-patterns',
      title: '分頁、篩選、版本與冪等鍵',
      en: 'API patterns',
      level: 2,
      summary: '列表 API 的分頁與篩選、破壞性改版的版本策略、避免重複下單的 Idempotency-Key。',
      example: { primary: 'cursor 分頁 + /v1 路徑版本', alts: ['offset 分頁', 'Header 版本'] },
      keywords: [],
      lab: null,
    },
    {
      id: 'resilience',
      title: '呼叫外部服務的韌性：timeout、重試、斷路器',
      en: 'Resilient outbound calls',
      level: 2,
      summary: '每個對外呼叫都要有 timeout；重試要退避、有上限、只重試冪等操作；連續失敗就斷路，讓自己活下來。',
      example: { primary: 'httpx 設 timeout + tenacity 重試', alts: ['service mesh 層的重試 / 斷路', '雲端 API gateway'] },
      keywords: ['Python'],
      lab: null,
    },
    {
      id: 'openapi',
      title: 'OpenAPI 與 API 契約',
      en: 'OpenAPI',
      level: 2,
      summary: '用機器可讀的規格描述 API，自動產生文件、前端 client、驗證與測試。',
      example: { primary: 'OpenAPI 3.1（FastAPI 自動產生）', alts: ['GraphQL schema', 'Protobuf'] },
      keywords: ['Python'],
      lab: null,
    },
    {
      id: 'cors-cookies',
      title: 'CORS、Cookie 與同源',
      en: 'CORS & cookies',
      level: 2,
      summary: '從伺服器這一端看 CORS：preflight 要回什麼、credentials 怎麼放行、cookie 的 SameSite / Secure / HttpOnly。',
      example: { primary: 'FastAPI CORSMiddleware', alts: ['nginx add_header', 'API gateway'] },
      keywords: ['nginx'],
      lab: null,
    },
    {
      id: 'http-caching',
      title: 'HTTP 快取與條件請求',
      en: 'HTTP caching',
      level: 2,
      summary: 'Cache-Control 決定誰能存多久、ETag / Last-Modified 讓客戶端問「有變嗎」、CDN 幫你擋掉大部分流量。',
      example: { primary: 'Cache-Control + ETag', alts: ['CDN（Cloudflare 等）', 'Redis 應用層快取'] },
      keywords: ['nginx'],
      lab: null,
    },
    {
      id: 'tls-dns',
      title: 'DNS、TLS 與憑證',
      en: 'DNS & TLS',
      level: 2,
      summary: '網域怎麼解析到你的機器、HTTPS 的憑證從哪來、在哪裡終結 TLS。',
      example: { primary: "Let's Encrypt + nginx TLS 終結", alts: ['雲端負載平衡器終結 TLS', 'Cloudflare'] },
      keywords: ['nginx'],
      lab: null,
    },
    {
      id: 'beyond-rest',
      title: 'GraphQL、gRPC、WebSocket 與 Webhook',
      en: 'Beyond REST',
      level: 3,
      summary: 'REST 之外的四種通訊形式，各自解決什麼問題、什麼時候不要用。',
      example: { primary: 'REST 為主，按需求加', alts: ['GraphQL', 'gRPC', 'WebSocket / SSE', 'Webhook'] },
      keywords: [],
      lab: null,
    },
  ],
}
