// 領域 2：網路、HTTP 與 API 設計
export default {
  id: 'web',
  no: 2,
  title: '網路、HTTP 與 API 設計',
  en: 'HTTP & API DESIGN',
  color: 'aqua',
  tagline: 'HTTP 的另一端：由你決定狀態碼、標頭與資源長什麼樣。',
  desc: 'API 是後端對外的合約。這一區把 HTTP 從「fetch 就好」拆成看得見的步驟，再學怎麼設計別人用起來不會罵的 REST API：資源、方法、狀態碼、分頁、錯誤格式、版本。',
  skills: [
    {
      id: 'http-basics',
      title: '一個 HTTP 請求的一生',
      en: 'HTTP fundamentals',
      level: 1,
      summary: 'DNS → TCP → TLS → 請求 → 伺服器 → 回應 → 快取，每一步都可能是延遲或 bug 的來源。',
      example: { primary: 'HTTP/1.1 + HTTP/2', alts: ['HTTP/3 (QUIC)'] },
      keywords: [],
      lab: 'HttpLab',
      points: [
        { b: 'HTTP 是無狀態的', t: '每個請求自帶全部資訊（標頭、cookie、token）。「登入狀態」是靠 session 或 token 在每次請求重建出來的。' },
        { b: '連線很貴，重用它', t: 'TCP 三向交握 + TLS 握手要來回好幾趟。keep-alive / HTTP/2 多工讓同一條連線跑很多請求；後端呼叫外部服務也要用連線池。' },
        { b: '標頭各司其職', t: '`Content-Type` 說 body 格式、`Authorization` 帶憑證、`Cache-Control` / `ETag` 管快取、`Set-Cookie` 種 cookie、`Location` 指新位置。' },
        { b: '狀態碼是 API 的第一層語意', t: '2xx 成功、3xx 去別處、4xx 客戶端的錯、5xx 伺服器的錯。回錯狀態碼會讓監控、重試、快取全部判斷錯。' },
        { b: '冪等與安全方法', t: 'GET / HEAD 安全（不改狀態）；GET / PUT / DELETE 冪等（重複執行結果相同）；POST 兩者都不是——重試邏輯與快取都靠這個性質。' },
      ],
      checklist: [
        '能說出一個 HTTPS 請求從輸入網址到拿到回應經過的 7 個階段',
        '能為常見情境挑對狀態碼：找不到、沒登入、沒權限、驗證失敗、伺服器炸了',
        '能解釋為什麼 PUT 冪等而 POST 不是',
      ],
      refs: [
        { label: 'MDN：HTTP', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP' },
        { label: 'MDN：HTTP 狀態碼', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status' },
        { label: 'RFC 9110：HTTP Semantics', url: 'https://datatracker.ietf.org/doc/html/rfc9110' },
      ],
    },
    {
      id: 'rest-design',
      title: 'REST API 設計',
      en: 'REST design',
      level: 1,
      summary: '資源是名詞、方法是動詞、狀態碼是結果——把這三件事對齊，API 就好用。',
      example: { primary: 'REST over JSON', alts: ['GraphQL', 'gRPC'] },
      keywords: [],
      lab: 'RestLab',
      points: [
        { b: '先畫資源樹', t: '`/orders`、`/orders/{id}`、`/orders/{id}/items`。動作用 HTTP 方法表達，不要 `/getOrders`、`/orders/delete/42`。' },
        { b: 'PUT 取代整筆、PATCH 部分更新', t: '兩者都對 `/orders/{id}`；PUT 少給欄位等於清空，PATCH 只改給的欄位。團隊要選定一種語意並寫進規範。' },
        { b: '建立回 201 + Location，刪除回 204', t: '成功的細節也要精準：建立成功回 201 並帶新資源位置；刪除成功沒有 body 就回 204。' },
        { b: '非 CRUD 的動作', t: '「取消訂單」可以是 `POST /orders/{id}/cancel`，或把它建模成狀態轉移 `PATCH /orders/{id}` `{"status": "cancelled"}`。兩者都可，一致最重要。' },
        { b: '錯誤回應統一格式', t: '固定 `{"error": {"code": "ORDER_NOT_FOUND", "message": "...", "details": [...]}}`，前端才能統一處理；RFC 9457 的 problem+json 是現成標準。' },
      ],
      checklist: [
        '能為「訂單」資源設計 6 個 endpoint 並標出方法、路徑、成功狀態碼',
        '能說明 PUT 與 PATCH 的差異並選一種寫進團隊規範',
        '能設計一個所有 endpoint 共用的錯誤回應格式',
      ],
      refs: [
        { label: 'RFC 9457：Problem Details for HTTP APIs', url: 'https://datatracker.ietf.org/doc/html/rfc9457' },
      ],
    },
    {
      id: 'api-patterns',
      title: '分頁、篩選、版本與冪等鍵',
      en: 'API patterns',
      level: 2,
      summary: '列表 API 的分頁與篩選、破壞性改版的版本策略、避免重複下單的 Idempotency-Key。',
      example: { primary: 'cursor 分頁 + /v1 路徑版本', alts: ['offset 分頁', 'Header 版本'] },
      keywords: [],
      lab: null,
      points: [
        { b: 'offset 分頁在深頁會慢', t: '`OFFSET 100000` 資料庫還是得掃過前十萬列。cursor 分頁用「上一頁最後一筆的排序鍵」當起點（`WHERE id > ?`），永遠走索引。' },
        { b: '篩選與排序要白名單', t: '允許哪些欄位可以 filter / sort 要明列，否則 `?sort=password` 之類的怪事會發生，也可能變成慢查詢。' },
        { b: '版本：能不改就不改', t: '加欄位不算破壞；改欄位語意、刪欄位才要新版本。路徑版本 `/v1` 最直白；避免同時維護超過兩個版本。' },
        { b: 'Idempotency-Key 防重複', t: '客戶端對「建立」請求帶唯一 key，伺服器記住 key → 結果，重送同 key 回同結果而不是再建一筆。付款、下單必備。' },
      ],
      checklist: [
        '能實作 cursor 分頁並解釋為何比 offset 好',
        '能列出哪些 API 變更是破壞性的、哪些不是',
        '知道 Idempotency-Key 的實作要存什麼、存多久',
      ],
      refs: [],
    },
    {
      id: 'resilience',
      title: '呼叫外部服務的韌性：timeout、重試、斷路器',
      en: 'Resilient outbound calls',
      level: 2,
      summary: '每個對外呼叫都要有 timeout；重試要退避、有上限、只重試冪等操作；連續失敗就斷路，讓自己活下來。',
      example: { primary: 'httpx 設 timeout + tenacity 重試', alts: ['service mesh 層的重試 / 斷路', '雲端 API gateway'] },
      keywords: ['Python'],
      lab: null,
      points: [
        { b: '沒有 timeout 就是無上限的等待', t: '`httpx.Client(timeout=5.0)`、DB `statement_timeout`、佇列任務 time limit。連線與讀取分開設；預設值通常是「永遠等」。' },
        { b: '重試要退避加抖動', t: '失敗後等 0.5s、1s、2s… 再加隨機抖動，避免所有客戶端同時重打（thundering herd）。次數有上限，總時間有上限。' },
        { b: '只重試冪等的、只重試值得的', t: 'GET / PUT / DELETE 可重試；POST 要有 Idempotency-Key 才能。5xx、逾時、連線錯誤值得重試；4xx 不值得（再打也一樣）。' },
        { b: '斷路器：連續失敗就先不打', t: '錯誤率超過門檻就「打開」一段時間直接快速失敗（回降級結果或錯誤），期間偶爾放一個請求試探，成功再「關上」。保護自己也保護對方。' },
        { b: '降級與隔離', t: '推薦系統掛了就顯示熱門商品；不同依賴用不同連線池（bulkhead），一個慢不會吃光全部。' },
      ],
      checklist: [
        '專案裡每個對外 HTTP 呼叫都有明確的 timeout',
        '能寫出「退避 + 抖動 + 上限」的重試，並說明哪些請求不能重試',
        '能解釋斷路器的三個狀態與切換條件',
      ],
      refs: [
        { label: 'httpx：Timeouts', url: 'https://www.python-httpx.org/advanced/timeouts/' },
      ],
    },
    {
      id: 'openapi',
      title: 'OpenAPI 與 API 契約',
      en: 'OpenAPI',
      level: 2,
      summary: '用機器可讀的規格描述 API，自動產生文件、前端 client、驗證與測試。',
      example: { primary: 'OpenAPI 3.1（FastAPI 自動產生）', alts: ['GraphQL schema', 'Protobuf'] },
      keywords: ['Python'],
      lab: null,
      points: [
        { b: 'FastAPI 從型別自動產出規格', t: 'pydantic model + 路由宣告 = `/openapi.json` + Swagger UI，零額外工作。這是選它當範例的原因之一。' },
        { b: 'code-first 與 schema-first', t: '從程式碼產規格（FastAPI）適合小團隊快速迭代；先寫規格再實作適合多團隊並行。兩者都要把規格當合約看待。' },
        { b: '用規格產 client', t: 'openapi-typescript、orval 等工具把規格變成型別安全的前端呼叫；後端改了回應型別，前端編譯就會失敗——這是好事。' },
        { b: '規格差異當 CI 檢查', t: '比對 PR 前後的 openapi.json，破壞性變更要顯式標記，避免默默改壞前端。' },
      ],
      checklist: [
        '能打開自己服務的 /docs，並解釋每個欄位的型別從哪裡來',
        '能用 OpenAPI 規格產出前端 client 並在前端專案使用',
      ],
      refs: [
        { label: 'OpenAPI Specification', url: 'https://spec.openapis.org/oas/latest.html' },
      ],
    },
    {
      id: 'cors-cookies',
      title: 'CORS、Cookie 與同源',
      en: 'CORS & cookies',
      level: 2,
      summary: '從伺服器這一端看 CORS：preflight 要回什麼、credentials 怎麼放行、cookie 的 SameSite / Secure / HttpOnly。',
      example: { primary: 'FastAPI CORSMiddleware', alts: ['nginx add_header', 'API gateway'] },
      keywords: ['nginx'],
      lab: null,
      points: [
        { b: 'CORS 是瀏覽器的規則，不是伺服器的防線', t: 'curl 不理 CORS。它保護的是「使用者的瀏覽器不被其他網站拿去打你的 API」，真正的授權還是要靠 token / session。' },
        { b: 'preflight 的來回', t: '非簡單請求（自訂標頭、JSON、PUT）先送 `OPTIONS`，伺服器回 `Access-Control-Allow-Origin / Methods / Headers`，通過才送真請求。`Access-Control-Max-Age` 可快取這個結果。' },
        { b: '帶 cookie 的請求規則更嚴', t: '`Access-Control-Allow-Credentials: true` 時 origin 不能是 `*`，必須明列。' },
        { b: 'Cookie 三個旗標', t: '`HttpOnly`（JS 讀不到，防 XSS 偷）、`Secure`（只走 HTTPS）、`SameSite=Lax/Strict`（防 CSRF）。session id 與 refresh token 放 cookie 時三個都要。' },
      ],
      checklist: [
        '能寫出允許前端 dev server 帶 cookie 呼叫 API 的正確 CORS 設定',
        '能解釋為什麼 CORS 不是安全機制、真正的防線是什麼',
        '能說出 HttpOnly / Secure / SameSite 各防什麼',
      ],
      refs: [
        { label: 'MDN：CORS', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS' },
      ],
    },
    {
      id: 'http-caching',
      title: 'HTTP 快取與條件請求',
      en: 'HTTP caching',
      level: 2,
      summary: 'Cache-Control 決定誰能存多久、ETag / Last-Modified 讓客戶端問「有變嗎」、CDN 幫你擋掉大部分流量。',
      example: { primary: 'Cache-Control + ETag', alts: ['CDN（Cloudflare 等）', 'Redis 應用層快取'] },
      keywords: ['nginx'],
      lab: null,
      points: [
        { b: '`Cache-Control` 的幾個字', t: '`no-store`（別存）、`no-cache`（存但每次要驗證）、`max-age=60`（60 秒內直接用）、`private`（只有瀏覽器能存，CDN 不行）、`public`。' },
        { b: '304 Not Modified', t: '回應帶 `ETag`，客戶端下次帶 `If-None-Match`；沒變就回 304 不帶 body，省頻寬也省序列化。' },
        { b: 'API 回應多半 `private, no-cache`', t: '個人化資料不能被共用快取存；公開且變動慢的資料（商品目錄）才給 `public, max-age`。' },
        { b: '靜態資產用檔名 hash + 長快取', t: '`app.abc123.js` 配 `max-age=31536000, immutable`：檔名帶內容 hash，改了內容就是新檔名，舊快取自然失效。這是 nginx / CDN 層的事。' },
      ],
      checklist: [
        '能為「個人訂單列表」「公開商品頁」「靜態 JS」各挑一組正確的快取標頭',
        '能實作 ETag 並讓客戶端拿到 304',
      ],
      refs: [
        { label: 'MDN：HTTP caching', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching' },
      ],
    },
    {
      id: 'tls-dns',
      title: 'DNS、TLS 與憑證',
      en: 'DNS & TLS',
      level: 2,
      summary: '網域怎麼解析到你的機器、HTTPS 的憑證從哪來、在哪裡終結 TLS。',
      example: { primary: "Let's Encrypt + nginx TLS 終結", alts: ['雲端負載平衡器終結 TLS', 'Cloudflare'] },
      keywords: ['nginx'],
      lab: null,
      points: [
        { b: 'DNS 紀錄的幾種', t: 'A / AAAA 指 IP、CNAME 指另一個名字、TXT 做驗證。TTL 決定改紀錄多久生效——換機器前先把 TTL 調短。' },
        { b: 'TLS 握手在做什麼', t: '驗證伺服器憑證（CA 簽的）、協商金鑰、之後整條連線加密。TLS 1.3 把握手縮到一趟來回。' },
        { b: 'TLS 終結在邊界', t: '憑證只放在 nginx / 負載平衡器，內網用 HTTP。後端要靠 `X-Forwarded-Proto` 知道原始請求是 HTTPS。' },
        { b: '憑證自動更新', t: "Let's Encrypt 憑證 90 天，而且業界已決議逐步把公開憑證最長效期縮到 47 天（2029 年前分階段）——手動換憑證不再可行，用 certbot / acme.sh 自動續，並監控到期日。" },
      ],
      checklist: [
        '能解釋瀏覽器如何判斷一張憑證可信',
        '能設定 nginx 做 TLS 終結並把 HTTP 導向 HTTPS',
        '知道憑證到期怎麼被監控與自動更新',
      ],
      refs: [
        { label: "Let's Encrypt 文件", url: 'https://letsencrypt.org/docs/' },
        { label: 'RFC 8446：TLS 1.3', url: 'https://datatracker.ietf.org/doc/html/rfc8446' },
      ],
    },
    {
      id: 'beyond-rest',
      title: 'GraphQL、gRPC、WebSocket 與 Webhook',
      en: 'Beyond REST',
      level: 3,
      summary: 'REST 之外的四種通訊形式，各自解決什麼問題、什麼時候不要用。',
      example: { primary: 'REST 為主，按需求加', alts: ['GraphQL', 'gRPC', 'WebSocket / SSE', 'Webhook'] },
      keywords: [],
      lab: null,
      points: [
        { b: 'GraphQL：前端決定要什麼欄位', t: '解決 over/under-fetching，但後端要處理 N+1（DataLoader）、查詢複雜度限制、快取變難。適合多端、多變的前端需求。' },
        { b: 'gRPC：服務對服務', t: 'Protobuf 二進位 + HTTP/2，型別強、效能好，但瀏覽器直接用不方便。微服務之間常見。' },
        { b: 'WebSocket 與 SSE：伺服器主動推', t: '聊天、即時通知用 WebSocket（雙向）；只需要伺服器 → 客戶端的用 SSE 更簡單，還能走一般 HTTP 基礎設施。' },
        { b: 'Webhook：你打別人', t: '事件發生時 POST 到對方的 URL。要簽章（HMAC）讓對方驗證來源、要重試與冪等（對方可能收到兩次）。' },
      ],
      checklist: [
        '能為「即時聊天」「行動 App 的首頁」「付款完成通知第三方」各選一種形式並說明理由',
        '知道 Webhook 為什麼要簽章與重試',
      ],
      refs: [],
    },
  ],
}
