// 領域 3：資料儲存（關聯式：PostgreSQL；文件式：MongoDB；快取：Redis）
// 技能內文（points / checklist / refs）在 ./body/d3-data.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'data',
  no: 3,
  title: '資料儲存',
  en: 'DATABASES & STORAGE',
  color: 'violet',
  tagline: 'SQL 看得見：JOIN、索引、交易用畫面理解，再學文件資料庫與快取怎麼補位。',
  desc: '後端最難補的基礎是資料庫，因為它的行為藏在引擎裡看不到。這一區把 JOIN、索引、交易畫出來，用 PostgreSQL 當關聯式範例、MongoDB 當文件式範例、Redis 當快取範例，最後談怎麼選。',
  skills: [
    {
      id: 'sql-basics',
      title: 'SQL 基礎：SELECT 到 GROUP BY',
      en: 'SQL fundamentals',
      level: 1,
      summary: 'SELECT / WHERE / ORDER BY / LIMIT / GROUP BY / HAVING 的執行順序，以及 NULL 的三值邏輯。',
      example: { primary: 'PostgreSQL', alts: ['MySQL / MariaDB', 'SQLite'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: null,
    },
    {
      id: 'sql-joins',
      title: 'JOIN 七兄弟',
      en: 'JOINs',
      level: 1,
      summary: 'INNER / LEFT / RIGHT / FULL 與三種排除式 JOIN，用文氏圖與真實結果表對照。',
      example: { primary: 'PostgreSQL', alts: ['MySQL（沒有 FULL JOIN）'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: 'SqlJoinLab',
    },
    {
      id: 'data-modeling',
      title: '資料建模與正規化',
      en: 'Data modeling',
      level: 2,
      summary: '主鍵、外鍵、唯一約束、1NF 到 3NF，以及什麼時候刻意反正規化。',
      example: { primary: 'PostgreSQL DDL + 約束', alts: ['任何關聯式資料庫'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: null,
    },
    {
      id: 'indexes',
      title: '索引與查詢計畫',
      en: 'Indexes & EXPLAIN',
      level: 2,
      summary: 'B-tree 索引為什麼把 O(n) 變 O(log n)、什麼時候索引不會被用、怎麼讀 EXPLAIN。',
      example: { primary: 'PostgreSQL B-tree + EXPLAIN ANALYZE', alts: ['MySQL InnoDB', 'MongoDB 索引'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: 'IndexLab',
    },
    {
      id: 'transactions',
      title: '交易、ACID 與隔離等級',
      en: 'Transactions',
      level: 2,
      summary: 'BEGIN / COMMIT / ROLLBACK 保證一組操作全做或全不做；隔離等級決定並發時你看得到什麼。',
      example: { primary: 'PostgreSQL（MVCC）', alts: ['MySQL InnoDB'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: null,
    },
    {
      id: 'sql-advanced',
      title: '子查詢、CTE 與視窗函數',
      en: 'Advanced SQL',
      level: 3,
      summary: '把複雜查詢拆成可讀的步驟（WITH）、在不縮減列數的情況下做排名與累計（OVER）。',
      example: { primary: 'PostgreSQL', alts: ['多數現代關聯式資料庫都支援'] },
      keywords: ['SQL', 'PostgreSQL'],
      lab: null,
    },
    {
      id: 'orm-migrations',
      title: 'ORM 與 migration',
      en: 'ORM & migrations',
      level: 2,
      summary: 'ORM 把表映射成物件、migration 把 schema 變更版本化——以及 ORM 最大的坑 N+1。',
      example: { primary: 'SQLAlchemy 2.0 + Alembic', alts: ['Django ORM', 'Prisma', 'Drizzle'] },
      keywords: ['Python', 'SQL', 'PostgreSQL'],
      lab: null,
    },
    {
      id: 'db-operations',
      title: '資料庫維運：備份還原、連線池、慢查詢',
      en: 'Database operations',
      level: 2,
      summary: '備份要演練還原、連線數要算、慢查詢要有 log、VACUUM 要知道在做什麼——資料庫上線後的日常。',
      example: { primary: 'PostgreSQL：pg_dump / pg_restore、pgbouncer、log_min_duration_statement', alts: ['受管服務（RDS、Cloud SQL）的自動備份與 PITR'] },
      keywords: ['PostgreSQL', 'Docker'],
      lab: null,
    },
    {
      id: 'mongodb',
      title: 'MongoDB 文件模型',
      en: 'Document model',
      level: 1,
      summary: '文件 = JSON、collection = 表但沒有固定 schema；嵌入還是參照是最重要的設計決定。',
      example: { primary: 'MongoDB', alts: ['Firestore', 'DynamoDB', 'CouchDB'] },
      keywords: ['MongoDB'],
      lab: 'DocVsRelLab',
    },
    {
      id: 'mongodb-ops',
      title: 'MongoDB 查詢、聚合與索引',
      en: 'MongoDB in practice',
      level: 2,
      summary: '查詢運算子、aggregation pipeline 的階段式思考、索引與 explain。',
      example: { primary: 'MongoDB + Motor / PyMongo', alts: [] },
      keywords: ['MongoDB', 'Python'],
      lab: null,
    },
    {
      id: 'redis-cache',
      title: 'Redis 與快取策略',
      en: 'Caching with Redis',
      level: 2,
      summary: 'cache-aside 流程、TTL 與失效、快取一致性為什麼難、Redis 除了快取還能做什麼。',
      example: { primary: 'Redis', alts: ['Memcached', 'Valkey', '應用程式內記憶體快取'] },
      keywords: [],
      lab: 'CacheLab',
    },
    {
      id: 'db-choice',
      title: '關聯式 vs 非關聯式怎麼選',
      en: 'Choosing a database',
      level: 2,
      summary: '從一致性、查詢模式、擴展方式、團隊熟悉度四個角度決定，而不是流行度。',
      example: { primary: 'PostgreSQL 為預設，有明確理由才換', alts: ['MongoDB', 'Redis', 'ClickHouse（分析）', 'Elasticsearch（搜尋）'] },
      keywords: ['PostgreSQL', 'MongoDB'],
      lab: null,
    },
  ],
}
