// 領域 4：驗證與授權（AuthN & AuthZ）
// 技能內文（points / checklist / refs）在 ./body/d4-auth.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'auth',
  no: 4,
  title: '驗證與授權',
  en: 'AUTHENTICATION & AUTHORIZATION',
  color: 'orange',
  tagline: '你是誰（驗證）與你能做什麼（授權）是兩件事：Session、Token、JWT、OAuth、RBAC、ABAC 各管一段。',
  desc: 'Token、JWT、OAuth、RBAC、ABAC 這些詞常一起出現，其實分屬不同層：怎麼證明身分、怎麼把身分帶在請求裡、怎麼委託第三方登入、怎麼決定權限。這一區用實驗室把每一段畫出來。',
  skills: [
    {
      id: 'authn-basics',
      title: '驗證基礎：Session vs Token',
      en: 'Sessions vs tokens',
      level: 1,
      summary: 'HTTP 無狀態，所以「登入過」要靠伺服器記（session）或客戶端帶證明（token）。',
      example: { primary: 'Cookie session（伺服器端儲存）', alts: ['Bearer token', 'JWT'] },
      keywords: ['Token'],
      lab: null,
    },
    {
      id: 'jwt',
      title: 'JWT 解剖',
      en: 'JSON Web Token',
      level: 2,
      summary: 'header.payload.signature 三段，payload 誰都能讀、簽章保證沒被改、exp 決定壽命。',
      example: { primary: 'JWT（HS256 / RS256）', alts: ['PASETO', 'opaque token + introspection'] },
      keywords: ['Token', 'JWT'],
      lab: 'JwtLab',
    },
    {
      id: 'oauth-oidc',
      title: 'OAuth 2.0 與 OpenID Connect',
      en: 'OAuth 2.0 & OIDC',
      level: 2,
      summary: '「用 Google 登入」背後的授權碼流程：導向、同意、拿 code、換 token、呼叫 API。',
      example: { primary: 'Authorization Code + PKCE', alts: ['Client Credentials（服務對服務）', 'Device Code'] },
      keywords: ['OAuth', 'Token'],
      lab: 'OAuthLab',
    },
    {
      id: 'rbac-abac',
      title: 'RBAC 與 ABAC 授權模型',
      en: 'RBAC & ABAC',
      level: 2,
      summary: '角色決定權限（RBAC）簡單好懂；屬性與政策決定（ABAC）彈性但複雜。實務多混用。',
      example: { primary: 'RBAC + 擁有權檢查', alts: ['ABAC（OPA / Casbin）', 'ReBAC（Zanzibar 類）'] },
      keywords: ['RBAC', 'ABAC'],
      lab: 'AccessControlLab',
    },
    {
      id: 'auth-in-practice',
      title: '驗證授權落地：middleware 與 dependency',
      en: 'Auth in practice',
      level: 2,
      summary: '把「取得目前使用者」「檢查權限」寫成可重用的依賴，讓每個 endpoint 一行搞定。',
      example: { primary: 'FastAPI Depends', alts: ['Django permissions', 'NestJS guards', 'Express middleware'] },
      keywords: ['Python', 'JWT', 'RBAC'],
      lab: null,
    },
    {
      id: 'api-keys-mfa',
      title: 'API key、服務間驗證、MFA 與 SSO',
      en: 'Machine auth, MFA, SSO',
      level: 3,
      summary: '沒有「使用者」的呼叫怎麼驗（API key、client credentials、mTLS）、多因素、企業 SSO。',
      example: { primary: 'API key（雜湊儲存）+ OAuth client credentials', alts: ['mTLS', 'SAML SSO', 'TOTP MFA'] },
      keywords: ['OAuth', 'Token'],
      lab: null,
    },
  ],
}
