// 領域 6：容器與部署（Docker、docker-compose、nginx）
// 技能內文（points / checklist / refs）在 ./body/d6-deploy.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'deploy',
  no: 6,
  title: '容器與部署',
  en: 'CONTAINERS & DEPLOYMENT',
  color: 'yellow',
  tagline: 'Docker 把「在我電腦可以跑」變成可攜的 image；compose 起整套；nginx 站在最前面。',
  desc: '部署是後端與「機器」交手的地方。這一區把 image 的層、compose 的網路、nginx 的分派畫成看得見的圖，再談環境設定、應用伺服器與雲端基礎。',
  skills: [
    {
      id: 'linux-basics',
      title: 'Linux 與 shell 基礎',
      en: 'Linux essentials',
      level: 1,
      summary: 'ssh 進機器後能看程序、埠、log、磁碟與權限，能用 systemd 管服務——容器與雲端都建立在這之上。',
      example: { primary: 'Ubuntu / Debian + bash', alts: ['Alpine（容器內，注意 musl）', 'macOS 終端機（大多相通）'] },
      keywords: ['Docker', 'nginx'],
      lab: null,
    },
    {
      id: 'docker-basics',
      title: 'Docker：image、container、layer',
      en: 'Docker fundamentals',
      level: 1,
      summary: 'image 是唯讀的層疊模板、container 是它的執行實例；Dockerfile 每一行一層，順序決定快取。',
      example: { primary: 'Docker', alts: ['Podman', 'containerd / nerdctl'] },
      keywords: ['Docker'],
      lab: 'DockerLab',
    },
    {
      id: 'dockerfile-python',
      title: '幫 Python 專案寫好 Dockerfile',
      en: 'Production Dockerfile',
      level: 2,
      summary: 'slim base、uv 安裝、非 root 使用者、多階段建置、healthcheck——正式環境 image 的基本盤。',
      example: { primary: 'python:3.12-slim + uv', alts: ['distroless', 'alpine（小心 musl 相容性）'] },
      keywords: ['Docker', 'Python', 'uv'],
      lab: null,
    },
    {
      id: 'compose',
      title: 'docker-compose 開發環境',
      en: 'Docker Compose',
      level: 1,
      summary: '一份 YAML 起 API + PostgreSQL + Redis + nginx：服務名就是 hostname、volume 留資料、depends_on 管順序。',
      example: { primary: 'Docker Compose v2', alts: ['Tilt / Skaffold（k8s 本機）', 'devcontainer'] },
      keywords: ['docker-compose', 'Docker', 'nginx', 'PostgreSQL'],
      lab: 'ComposeLab',
    },
    {
      id: 'nginx',
      title: 'nginx 反向代理',
      en: 'Reverse proxy',
      level: 2,
      summary: 'nginx 站在最前面：終結 TLS、給靜態檔、把 /api 轉給後端、負載平衡、限流、擋掉壞請求。',
      example: { primary: 'nginx', alts: ['Caddy（自動 TLS）', 'Traefik（容器導向）', '雲端負載平衡器'] },
      keywords: ['nginx', 'Docker'],
      lab: 'NginxLab',
    },
    {
      id: 'config-12factor',
      title: '環境設定與 12-factor',
      en: 'Configuration',
      level: 2,
      summary: '同一份 image 靠環境變數跑在 dev / staging / prod；設定、程式碼、資料三者分離。',
      example: { primary: 'pydantic-settings 讀環境變數', alts: ['dotenv', 'config server'] },
      keywords: ['Docker', 'Python'],
      lab: null,
    },
    {
      id: 'process-servers',
      title: '應用伺服器與程序管理',
      en: 'App servers & processes',
      level: 2,
      summary: 'uvicorn / gunicorn 的 worker 模型、要開幾個、graceful shutdown、health / readiness 探針。',
      example: { primary: 'uvicorn（多 worker）', alts: ['gunicorn + uvicorn worker', 'granian'] },
      keywords: ['Python', 'Docker'],
      lab: null,
    },
    {
      id: 'cloud-basics',
      title: '雲端與主機基礎',
      en: 'Cloud basics',
      level: 3,
      summary: 'VM、容器平台、serverless 三種跑法；受管資料庫、物件儲存、DNS / CDN 是幾乎必用的積木。',
      example: { primary: '容器平台 + 受管 PostgreSQL + 物件儲存', alts: ['VM + docker compose（小專案）', 'Serverless（事件驅動）', 'Kubernetes（多服務、大團隊）'] },
      keywords: ['Docker'],
      lab: null,
    },
  ],
}
