// 領域 6：容器與部署（Docker、docker-compose、nginx）
export default {
  id: 'deploy',
  no: 6,
  title: '容器與部署',
  en: 'CONTAINERS & DEPLOYMENT',
  color: 'yellow',
  tagline: 'Docker 把「在我電腦可以跑」變成可攜的 image；compose 起整套；nginx 站在最前面。',
  desc: '部署是後端與「機器」交手的地方。這一區把 image 的層、compose 的網路、nginx 的分派畫成看得見的圖，再談環境設定、應用伺服器與雲端基礎。',
  skills: [
    {
      id: 'linux-basics',
      title: 'Linux 與 shell 基礎',
      en: 'Linux essentials',
      level: 1,
      summary: 'ssh 進機器後能看程序、埠、log、磁碟與權限，能用 systemd 管服務——容器與雲端都建立在這之上。',
      why: '服務出事時你會在一台 Linux 機器（或容器）裡，只有終端機。看不懂 ps、ss、journalctl，就只能重開機祈禱。',
      example: { primary: 'Ubuntu / Debian + bash', alts: ['Alpine（容器內，注意 musl）', 'macOS 終端機（大多相通）'] },
      keywords: ['Docker', 'nginx'],
      lab: null,
      points: [
        { b: '程序與訊號', t: '`ps aux`、`top`、`kill -TERM`（優雅停止）與 `-KILL`（強制）。容器的 PID 1 收到 SIGTERM 要能正確退出，否則 `docker stop` 會等 10 秒再硬殺。' },
        { b: '網路與埠', t: '`ss -ltnp` 看誰在聽哪個埠、`curl -v` 看完整請求回應、`dig` 查 DNS。「連不上」先分清是 DNS、防火牆、還是服務沒起來。' },
        { b: '檔案權限與使用者', t: '`chmod` / `chown`、`ls -l` 的 rwx、不要用 root 跑服務。容器裡的 UID 與掛載 volume 的權限問題就是這裡。' },
        { b: 'systemd 與 log', t: '`systemctl status/restart`、`journalctl -u 服務 -f`；容器外的服務由 systemd 管、開機自動起、崩潰自動重啟。' },
        { b: '環境變數、路徑與 shell 習慣', t: '`export`、`env`、`$PATH`、`set -euo pipefail` 讓腳本出錯就停；管線 `|`、`grep`、`awk`、`jq` 處理 log 與 JSON。' },
      ],
      checklist: [
        '能 ssh 進一台機器，找出佔用 8000 埠的程序並優雅地重啟它',
        '能用 journalctl 追一個 systemd 服務的即時 log',
        '能解釋 SIGTERM 與 SIGKILL 的差別，以及容器為什麼在意 PID 1',
      ],
      refs: [],
    },
    {
      id: 'docker-basics',
      title: 'Docker：image、container、layer',
      en: 'Docker fundamentals',
      level: 1,
      summary: 'image 是唯讀的層疊模板、container 是它的執行實例；Dockerfile 每一行一層，順序決定快取。',
      why: '你工作上天天 `docker compose up`，但 build 慢、image 肥、改一行全重 build——都是因為不懂層。',
      example: { primary: 'Docker', alts: ['Podman', 'containerd / nerdctl'] },
      keywords: ['Docker'],
      lab: 'DockerLab',
      points: [
        { b: 'image vs container', t: 'image 像 class、container 像 instance：同一個 image 可以跑很多 container，各自有一層可寫層，image 本身不變。' },
        { b: '每個指令一層，層可快取', t: '`COPY`、`RUN` 各產生一層；只要該層的輸入（檔案內容、指令）沒變就用快取。一旦某層失效，它之後的所有層都重做。' },
        { b: '順序：越少變的越前面', t: '先 `COPY pyproject.toml uv.lock` 再 `RUN uv sync`，最後才 `COPY . .`。改程式碼不會重裝依賴。' },
        { b: '.dockerignore', t: '排除 `.git`、`.venv`、`node_modules`、`.env`——不然 `COPY . .` 又肥又慢，還可能把 secret 帶進去。' },
        { b: 'container 是無狀態的', t: '容器刪掉可寫層就沒了。資料要放 volume 或外部服務；log 寫 stdout 讓 Docker 收。' },
      ],
      checklist: [
        '能解釋 image 與 container 的關係，以及 layer 快取怎麼運作',
        '能重排一份 Dockerfile 讓改程式碼不用重裝依賴',
        '能用 `docker image history` 看每層大小並指出可以瘦身的地方',
      ],
      refs: [
        { label: 'Docker 文件', url: 'https://docs.docker.com/' },
        { label: 'Docker：Build cache', url: 'https://docs.docker.com/build/cache/' },
      ],
    },
    {
      id: 'dockerfile-python',
      title: '幫 Python 專案寫好 Dockerfile',
      en: 'Production Dockerfile',
      level: 2,
      summary: 'slim base、uv 安裝、非 root 使用者、多階段建置、healthcheck——正式環境 image 的基本盤。',
      why: '「能跑」和「能上線」差很多：肥 image 拖慢部署、root 執行放大漏洞、沒 healthcheck 壞了沒人知道。',
      example: { primary: 'python:3.12-slim + uv', alts: ['distroless', 'alpine（小心 musl 相容性）'] },
      keywords: ['Docker', 'Python', 'uv'],
      lab: null,
      points: [
        { b: '固定 base image 版本', t: '`python:3.12-slim` 而非 `python:latest`；定期主動升級而不是被動被換。' },
        { b: '多階段建置', t: 'builder 階段裝 uv 與編譯工具、`uv sync --frozen --no-dev`；runtime 階段只 COPY `.venv` 與程式碼。最終 image 沒有編譯器。' },
        { b: '非 root 執行', t: '`RUN useradd -m app && USER app`。容器逃逸或應用漏洞時，攻擊者不是 root。' },
        { b: 'HEALTHCHECK 與正確的 CMD', t: '`CMD ["uvicorn", "app:app", "--host", "0.0.0.0"]` 用 exec 形式讓程序收得到 SIGTERM；`HEALTHCHECK` 打 `/health`（只有 Docker / Compose 會讀它，Kubernetes 用自己的 liveness / readiness probe）。' },
        { b: '環境變數的預設', t: '`PYTHONUNBUFFERED=1`（log 即時）、`PYTHONDONTWRITEBYTECODE=1`；設定值一律 runtime 注入。' },
      ],
      checklist: [
        '能寫出多階段、非 root、有 HEALTHCHECK 的 Python Dockerfile',
        '能說出為什麼 CMD 要用 exec 形式',
        'image 大小在合理範圍（slim base 通常 150–250MB）',
      ],
      refs: [
        { label: 'Docker：Multi-stage builds', url: 'https://docs.docker.com/build/building/multi-stage/' },
        { label: 'uv：Using uv in Docker', url: 'https://docs.astral.sh/uv/guides/integration/docker/' },
      ],
    },
    {
      id: 'compose',
      title: 'docker-compose 開發環境',
      en: 'Docker Compose',
      level: 1,
      summary: '一份 YAML 起 API + PostgreSQL + Redis + nginx：服務名就是 hostname、volume 留資料、depends_on 管順序。',
      why: '本機環境一致是團隊效率的基礎。新人 `docker compose up` 十分鐘能跑，比讀三頁安裝文件強。',
      example: { primary: 'Docker Compose v2', alts: ['Tilt / Skaffold（k8s 本機）', 'devcontainer'] },
      keywords: ['docker-compose', 'Docker', 'nginx', 'PostgreSQL'],
      lab: 'ComposeLab',
      points: [
        { b: '服務名 = DNS 名', t: 'api 連資料庫用 `postgresql://…@db:5432/app`，`db` 就是 compose 幫你解析的 hostname。不是 localhost。' },
        { b: '現在叫 `docker compose`', t: '舊的 `docker-compose`（v1、獨立二進位）已停止維護；現行是 Docker CLI 的子命令 `docker compose`，檔名慣例 `compose.yaml`。工作上聽到兩種說法指的是同一件事。' },
        { b: 'ports vs expose', t: '`ports: "5432:5432"` 發布到主機（你本機工具能連）；`expose` 只在 compose 網路內可見。正式環境不要把 DB 發布出去。' },
        { b: 'volume 讓資料活過重建', t: '`pgdata:/var/lib/postgresql/data`；`docker compose down` 不刪 volume、`down -v` 才刪。' },
        { b: 'depends_on 只管啟動順序', t: '要等 DB 真的能連，加 `healthcheck` 並用 `condition: service_healthy`。' },
        { b: 'override 分環境', t: '`compose.yaml` 放共同設定、`compose.override.yaml` 放本機（掛程式碼、開 debug）；CI 用另一份。' },
      ],
      checklist: [
        '能寫一份起 api + db + redis 的 compose，api 能透過服務名連到 db',
        '能解釋 ports 與 expose 的差別、volume 與 bind mount 的差別',
        '能用 healthcheck 讓 api 等 db 就緒再啟動',
      ],
      refs: [
        { label: 'Docker Compose 文件', url: 'https://docs.docker.com/compose/' },
      ],
    },
    {
      id: 'nginx',
      title: 'nginx 反向代理',
      en: 'Reverse proxy',
      level: 2,
      summary: 'nginx 站在最前面：終結 TLS、給靜態檔、把 /api 轉給後端、負載平衡、限流、擋掉壞請求。',
      why: '你工作上的流量都經過 nginx。知道 location 怎麼匹配、標頭怎麼轉，才能解「後端拿到的 IP 都是 127.0.0.1」這類問題。',
      example: { primary: 'nginx', alts: ['Caddy（自動 TLS）', 'Traefik（容器導向）', '雲端負載平衡器'] },
      keywords: ['nginx', 'Docker'],
      lab: 'NginxLab',
      points: [
        { b: '反向代理 vs 正向代理', t: '正向代理替客戶端出去（公司防火牆）；反向代理替伺服器接進來（客戶端只看到 nginx）。' },
        { b: 'location 匹配順序', t: '先找**最長的前綴匹配**；若它是 `=`（精確）或 `^~`，直接採用、不再看 regex；否則依設定檔順序試 `~` / `~*` regex，第一個命中的贏；都沒中才回頭用那個最長前綴。所以 `/api/` 與 `/` 同時存在時，`/api/users` 走前者。' },
        { b: 'proxy_set_header 轉真實資訊', t: '`Host $host`、`X-Real-IP $remote_addr`、`X-Forwarded-For`、`X-Forwarded-Proto $scheme`——後端才知道原始網域、IP 與是否 HTTPS。' },
        { b: 'upstream 與負載平衡', t: '`upstream api { server app1:8000; server app2:8000; }` 預設 round-robin；掛掉的暫時剔除；`least_conn` 給長連線。' },
        { b: '限流與緩衝', t: '`limit_req_zone` 依 IP 限速；nginx 幫慢客戶端緩衝 request / response，讓後端 worker 不被拖住。' },
      ],
      checklist: [
        '能寫出 SPA + `/api/` 反向代理 + TLS 的 nginx 設定',
        '能解釋四種 location 修飾詞的優先序',
        '能讓後端正確取得真實客戶端 IP 與 scheme',
      ],
      refs: [
        { label: 'nginx 文件', url: 'https://nginx.org/en/docs/' },
        { label: 'nginx：ngx_http_proxy_module', url: 'https://nginx.org/en/docs/http/ngx_http_proxy_module.html' },
      ],
    },
    {
      id: 'config-12factor',
      title: '環境設定與 12-factor',
      en: 'Configuration',
      level: 2,
      summary: '同一份 image 靠環境變數跑在 dev / staging / prod；設定、程式碼、資料三者分離。',
      why: '「正式環境連到測試資料庫」「debug 模式開在線上」都是設定管理失敗。12-factor 是二十年來的共識。',
      example: { primary: 'pydantic-settings 讀環境變數', alts: ['dotenv', 'config server'] },
      keywords: ['Docker', 'Python'],
      lab: null,
      points: [
        { b: '設定從環境讀，且要驗證', t: '`class Settings(BaseSettings): database_url: PostgresDsn; debug: bool = False`——啟動時缺值就失敗，不要等第一個請求才炸。' },
        { b: '一份 build、多個環境', t: 'image 不含環境資訊；部署時注入。這樣 staging 測過的東西才真的等於上線的東西。' },
        { b: 'dev / prod 差異最小化', t: '本機也用 PostgreSQL（不用 SQLite）、也跑在容器裡；差異只在設定值。' },
        { b: 'log 寫 stdout、背景工作是獨立程序', t: '容器平台負責收 log；排程與 worker 是獨立的 process type，不塞在 web 程序裡。' },
        { b: '設定要能列出來', t: '啟動時把（遮罩過的）設定印一次，出問題先確認「它到底讀到什麼」。' },
      ],
      checklist: [
        '能用 pydantic-settings 定義並驗證服務的所有設定',
        '能說出 12-factor 裡至少 6 條並解釋為什麼',
      ],
      refs: [
        { label: 'The Twelve-Factor App', url: 'https://12factor.net/' },
      ],
    },
    {
      id: 'process-servers',
      title: '應用伺服器與程序管理',
      en: 'App servers & processes',
      level: 2,
      summary: 'uvicorn / gunicorn 的 worker 模型、要開幾個、graceful shutdown、health / readiness 探針。',
      why: '「開發時 `uvicorn --reload` 就好，上線也這樣」會在第一次流量高峰出事。程序模型決定你能扛多少、更新時會不會斷。',
      example: { primary: 'uvicorn（多 worker）', alts: ['gunicorn + uvicorn worker', 'granian'] },
      keywords: ['Python', 'Docker'],
      lab: null,
      points: [
        { b: 'worker 數', t: 'I/O 密集的 async 服務通常 CPU 核心數個 worker 就夠；每個 worker 是獨立程序、各自的連線池。' },
        { b: '連線池上限要算', t: 'worker 數 × 每個 pool 大小 ≤ 資料庫 max_connections；否則流量一上來就 too many connections。' },
        { b: 'graceful shutdown', t: '收到 SIGTERM 停止接新請求、把進行中的做完、關連線、再退出。部署與擴縮時才不會噴 502。' },
        { b: 'liveness vs readiness', t: 'liveness 說「我還活著」（掛了就重啟）；readiness 說「我可以接流量」（DB 連上、暖機完）。負載平衡器看 readiness。' },
        { b: '超時要層層設', t: 'nginx proxy_read_timeout、應用層請求超時、資料庫 statement_timeout、外部呼叫 timeout——沒有超時的呼叫會把 worker 耗光。' },
      ],
      checklist: [
        '能為一台 4 核機器決定 worker 數與資料庫連線池大小',
        '服務有 /health 與 /ready 兩個端點且語意正確',
        '能說明 graceful shutdown 的步驟',
      ],
      refs: [
        { label: 'Uvicorn：Deployment', url: 'https://www.uvicorn.org/deployment/' },
      ],
    },
    {
      id: 'cloud-basics',
      title: '雲端與主機基礎',
      en: 'Cloud basics',
      level: 3,
      summary: 'VM、容器平台、serverless 三種跑法；受管資料庫、物件儲存、DNS / CDN 是幾乎必用的積木。',
      why: '部署到哪、怎麼算錢、什麼交給雲端管，是每個專案上線前要決定的事。知道選項才不會把 DB 自己裝在 VM 上然後半夜救。',
      example: { primary: '容器平台 + 受管 PostgreSQL + 物件儲存', alts: ['VM + docker compose（小專案）', 'Serverless（事件驅動）', 'Kubernetes（多服務、大團隊）'] },
      keywords: ['Docker'],
      lab: null,
      points: [
        { b: '三種跑法', t: 'VM 最自由最累；容器平台（Cloud Run、Fly.io、ECS、App Service）給 image 就跑、自動擴縮；serverless 函式按次計費、冷啟動與執行時間限制。' },
        { b: '資料庫交給受管服務', t: '備份、升級、高可用、監控——自己在 VM 上裝 PostgreSQL 省的錢遠不夠賠一次資料遺失。' },
        { b: '檔案放物件儲存', t: '使用者上傳、報表、備份放 S3 / GCS / R2，用 presigned URL 讓前端直傳。不放在應用伺服器磁碟。' },
        { b: '網路邊界', t: 'DB 與 Redis 在私有網路、只有 API 能連；對外只開 443；DNS + CDN 在最前面。' },
        { b: 'Kubernetes 不是起點', t: '它解決的是「很多服務、很多團隊」的問題。一個 API + 一個 DB 用容器平台或 compose on VM 就好。' },
      ],
      checklist: [
        '能為「單一 API + DB + 前端」的小產品畫出部署架構圖並估算主要成本項',
        '能說出何時該用受管資料庫、何時該用物件儲存',
      ],
      refs: [],
    },
  ],
}
