// 領域 7：CI/CD 與交付（GitHub Actions、GitLab CI）
// 技能內文（points / checklist / refs）在 ./body/d7-cicd.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'cicd',
  no: 7,
  title: 'CI/CD 與交付',
  en: 'CI/CD & DELIVERY',
  color: 'green',
  tagline: '每次 push 自動 lint、測試、build image、部署——GitHub Actions 與 GitLab CI 概念一樣、寫法對照。',
  desc: '交付是把「寫好的程式碼」變成「跑在正式環境的服務」的機械化流程。這一區對照 GitHub Actions 與 GitLab CI，再談部署策略、環境與 secrets、可觀測性與事故處理。',
  skills: [
    {
      id: 'git-workflow',
      title: 'Git 工作流與分支策略',
      en: 'Git workflow',
      level: 1,
      summary: '短命分支 + PR/MR + 保護的 main：trunk-based 是現代預設；commit 要能讀、要能 revert。',
      example: { primary: 'Trunk-based（短分支 + PR）', alts: ['GitHub Flow', 'Git Flow（release 分支，較重）'] },
      keywords: ['GitHub Actions', 'GitLab CI'],
      lab: null,
    },
    {
      id: 'ci-pipeline',
      title: 'CI 管線：lint、test、build',
      en: 'CI pipeline',
      level: 1,
      summary: 'push 觸發 → 裝依賴（有快取）→ lint → 測試（起 DB service）→ build image → 推到 registry。',
      example: { primary: 'GitHub Actions', alts: ['GitLab CI', 'CircleCI', 'Jenkins'] },
      keywords: ['GitHub Actions', 'GitLab CI', 'Docker', 'uv'],
      lab: 'PipelineLab',
    },
    {
      id: 'environments-secrets',
      title: '環境、secrets 與 artifact',
      en: 'Environments & artifacts',
      level: 2,
      summary: 'dev → staging → prod 各有自己的變數與審核規則；artifact 在 job 間傳；secret 由平台注入。',
      example: { primary: 'GitHub Environments + secrets', alts: ['GitLab environments + protected variables'] },
      keywords: ['GitHub Actions', 'GitLab CI', 'Docker'],
      lab: null,
    },
    {
      id: 'cd-strategies',
      title: '部署策略與資料庫遷移',
      en: 'Deployment strategies',
      level: 2,
      summary: 'rolling / blue-green / canary 各怎麼換版、怎麼回滾；migration 要跟程式碼相容才能零停機。',
      example: { primary: 'Rolling + 可回滾的 migration', alts: ['Blue-green', 'Canary + feature flag'] },
      keywords: ['Docker', 'PostgreSQL', 'GitHub Actions'],
      lab: null,
    },
    {
      id: 'observability',
      title: '可觀測性：log、metrics、trace',
      en: 'Observability',
      level: 2,
      summary: 'log 記發生了什麼、metrics 記數量與趨勢、trace 記一個請求跨服務的路徑；三者用 request id / trace id 串起來。',
      example: { primary: 'JSON log + Prometheus metrics + OpenTelemetry trace', alts: ['雲端內建（Cloud Logging / CloudWatch）', 'Sentry（錯誤追蹤）'] },
      keywords: ['Python', 'nginx', 'Docker'],
      lab: null,
    },
    {
      id: 'reliability',
      title: '健康檢查、備份與事故處理',
      en: 'Reliability basics',
      level: 3,
      summary: 'SLO 定義「夠好」、備份要演練還原、事故有 runbook 與不咎責的檢討。',
      example: { primary: 'SLO + runbook + postmortem', alts: [] },
      keywords: ['PostgreSQL', 'Docker'],
      lab: null,
    },
  ],
}
