// 領域 8：演算法與系統設計
export default {
  id: 'algo',
  no: 8,
  title: '演算法與系統設計',
  en: 'ALGORITHMS & SYSTEM DESIGN',
  color: 'magenta',
  tagline: '後端的演算法不是刷題：是 Big-O 直覺、幾個真的會用到的結構與演算法，以及把它們組成系統的思考框架。',
  desc: '你不需要背紅黑樹，但要知道為什麼索引是 log n、迴圈裡打 query 是 n²、限流用 token bucket、快取用 LRU。這一區挑後端真的會遇到的部分，最後給一個系統設計的思考順序。',
  skills: [
    {
      id: 'big-o',
      title: 'Big-O 與後端常見複雜度',
      en: 'Big-O intuition',
      level: 1,
      summary: 'O(1)、O(log n)、O(n)、O(n log n)、O(n²) 分別對應 hash 查詢、索引、全表掃描、排序、巢狀迴圈 / N+1。',
      why: '「資料量到十萬筆就爆」的 bug 幾乎都是複雜度問題。看到迴圈裡有 query，腦中要自動響警報。',
      example: { primary: 'Python 內建結構 + SQL 查詢計畫', alts: [] },
      keywords: ['SQL', 'Python'],
      lab: 'BigOLab',
      points: [
        { b: 'Big-O 是成長率', t: '不是秒數。它回答「資料變十倍時，時間變幾倍」：O(n) 十倍、O(n²) 百倍、O(log n) 幾乎不變。' },
        { b: '後端最貴的是 I/O 次數', t: '一次 DB 往返 ≈ 幾十萬次 CPU 運算。所以 O(n) 次查詢比 O(n²) 次記憶體運算還慘。' },
        { b: 'N+1 是 O(n) 次 I/O', t: '取 n 篇文章再各查作者 = n+1 次查詢。JOIN 或 `WHERE id IN (...)` 變 2 次。' },
        { b: 'dict / set 是 O(1)', t: 'Python 裡「在 list 裡找」是 O(n)、「在 set 裡找」是 O(1)。兩個 list 對照要先把一個轉成 dict。' },
        { b: '常數在小 n 時贏', t: 'n = 20 時 O(n) 掃描可能比走索引快，所以資料庫會自己選 Seq Scan。別為小資料過度優化。' },
      ],
      checklist: [
        '能為五種複雜度各舉一個後端例子',
        '能在 code review 時指出 N+1 與 list 巢狀查找',
      ],
      refs: [
        { label: 'Wikipedia：Big O notation', url: 'https://en.wikipedia.org/wiki/Big_O_notation' },
      ],
    },
    {
      id: 'data-structures',
      title: '後端常用資料結構',
      en: 'Data structures',
      level: 1,
      summary: 'hash map / set、陣列與佇列、堆（優先佇列）、樹（B-tree、trie）、圖——各自在後端哪裡出現。',
      why: '不是為了面試，是為了認出它們：Redis 的 sorted set 是跳躍表加 hash table、資料庫索引是 B+tree、任務排程是 heap、權限繼承是圖。',
      example: { primary: 'Python collections + Redis 資料型別', alts: [] },
      keywords: ['Python'],
      lab: null,
      points: [
        { b: 'hash map / set：O(1) 查找', t: '去重、對照表、計數（`Counter`）、快取。Redis 的 hash / set 也是。' },
        { b: 'deque / queue：先進先出', t: '工作佇列、滑動視窗、BFS。`collections.deque` 兩端 O(1)。' },
        { b: 'heap：永遠取最小 / 最大', t: '`heapq` 做排程（下一個到期的任務）、top-k、合併多個排序流。' },
        { b: 'B-tree：磁碟友善的排序樹', t: '一個節點裝很多 key、樹很矮 → 幾次磁碟讀取就找到。關聯式資料庫的預設索引嚴格說是 B+tree：資料只在葉節點、葉節點串成鏈，所以範圍掃描（BETWEEN、ORDER BY）特別快。' },
        { b: '圖：關係與依賴', t: '權限繼承、任務依賴（拓樸排序）、推薦、社交關係。DAG 的拓樸排序在 CI 排 job 順序也用到。' },
      ],
      checklist: [
        '能為「去重」「top 10」「任務排程」「依賴排序」各挑一個結構',
        '能解釋為什麼資料庫索引用 B-tree 而不是二元搜尋樹',
      ],
      refs: [
        { label: 'Python collections', url: 'https://docs.python.org/3/library/collections.html' },
        { label: 'Python heapq', url: 'https://docs.python.org/3/library/heapq.html' },
      ],
    },
    {
      id: 'rate-limiting',
      title: '限流演算法',
      en: 'Rate limiting',
      level: 2,
      summary: 'token bucket 允許短暴衝、固定視窗有邊界問題、滑動視窗較平滑；用 Redis 實作跨實例共享。',
      why: '登入、OTP、昂貴查詢沒有限流等於免費被打。這也是 OWASP A07 與 API Top 10 的重點。',
      example: { primary: 'Token bucket（Redis）', alts: ['nginx limit_req', 'API gateway 內建'] },
      keywords: ['nginx', 'OWASP'],
      lab: 'RateLimitLab',
      points: [
        { b: 'token bucket', t: '桶子固定速率補 token、每個請求拿一個、沒了就拒絕。容量決定能吃多大的暴衝，速率決定長期上限。' },
        { b: '固定視窗的邊界問題', t: '每分鐘 100 次：59 秒打 100 次、61 秒再打 100 次 = 2 秒內 200 次。滑動視窗（log 或加權）修正這點。' },
        { b: 'key 用什麼', t: '登入用帳號 + IP、API 用 user id 或 API key、公開端點用 IP（注意 NAT 後很多人共用一個 IP）。' },
        { b: '回應要說清楚', t: '429 + `Retry-After`、`X-RateLimit-Limit / Remaining / Reset`，客戶端才能正確退避。' },
        { b: '放在哪一層', t: 'nginx 擋粗的（每 IP）、應用層擋細的（每使用者、每動作）；多實例要用 Redis 共享計數。' },
      ],
      checklist: [
        '能用 Redis 實作 token bucket 或滑動視窗',
        '能說出固定視窗的問題與兩種修法',
      ],
      refs: [],
    },
    {
      id: 'lru-cache',
      title: 'LRU 與快取淘汰',
      en: 'Cache eviction',
      level: 2,
      summary: '記憶體有限，快取滿了淘汰誰：LRU（最久沒用）最常見、LFU 看頻率、TTL 看時間。',
      why: 'Redis 滿了怎麼辦、`lru_cache` 為什麼要設 maxsize——淘汰策略選錯，快取命中率會很難看。',
      example: { primary: 'LRU（functools.lru_cache、Redis allkeys-lru）', alts: ['LFU', 'FIFO', 'TTL-only'] },
      keywords: ['Python'],
      lab: null,
      points: [
        { b: 'LRU 的實作', t: 'hash map + 雙向鏈結串列：查找 O(1)、每次存取把節點移到頭、滿了砍尾。Python 的 `OrderedDict` 幾行就能寫。' },
        { b: 'Redis 的 maxmemory-policy', t: '`allkeys-lru`（全部都可淘汰）、`volatile-lru`（只淘汰有 TTL 的）、`noeviction`（滿了就報錯）。當快取用要設前者。' },
        { b: '程序內快取的陷阱', t: '`lru_cache` 每個 worker 各一份、重啟就沒、多實例不一致。適合純函式與設定，不適合使用者資料。' },
        { b: '命中率是唯一指標', t: '監控 hit / (hit + miss)；低於預期就檢查 key 設計、TTL、容量。' },
      ],
      checklist: [
        '能用 OrderedDict 實作一個 LRU cache',
        '能說出 allkeys-lru 與 volatile-lru 的差別',
      ],
      refs: [
        { label: 'Redis：Key eviction', url: 'https://redis.io/docs/latest/develop/reference/eviction/' },
      ],
    },
    {
      id: 'queues-workers',
      title: '訊息佇列與背景工作',
      en: 'Queues & workers',
      level: 2,
      summary: '寄信、產報表、呼叫慢的第三方——丟進佇列讓 worker 做，API 立刻回；消費者要冪等。',
      why: 'API 在請求裡做 30 秒的事會超時、會被重試、會拖垮 worker。非同步化是後端擴展的第一步。',
      example: { primary: 'Redis + RQ / Celery / arq', alts: ['RabbitMQ', 'Kafka（事件流）', '雲端佇列（SQS、Pub/Sub）'] },
      keywords: ['Python'],
      lab: null,
      points: [
        { b: '生產者 / 佇列 / 消費者', t: 'API 把任務（含參數）放進佇列就回 202；worker 程序取出執行；狀態存 DB 讓前端輪詢或推播。' },
        { b: 'at-least-once 代表會重複', t: 'worker 做到一半掛了任務會重投，所以消費者要冪等：用任務 id 去重、或操作本身可重複執行。' },
        { b: '重試與死信', t: '失敗重試要指數退避、有上限；超過就進死信佇列給人看，不要無限重試塞爆佇列。' },
        { b: 'outbox 模式', t: '「存 DB 並發事件」要原子：事件先寫進同一交易的 outbox 表，再由另一個程序送出。直接在交易裡發 MQ 會有一邊成功一邊失敗。' },
        { b: 'Kafka 不是任務佇列', t: '它是可重播的事件日誌，適合多消費者、事件溯源；單純的背景任務用 Redis / RabbitMQ 簡單得多。' },
      ],
      checklist: [
        '能把「註冊後寄歡迎信」改成佇列 + worker，且重複執行不會寄兩封',
        '能說出 at-least-once 與 exactly-once 的差別',
      ],
      refs: [],
    },
    {
      id: 'scaling',
      title: '擴展：無狀態、負載平衡、讀寫分離',
      en: 'Scaling',
      level: 3,
      summary: 'API 無狀態就能水平擴展；資料庫先垂直、再讀寫分離、最後分片；快取與佇列吸收尖峰。',
      why: '「加機器」只對無狀態的東西有效。知道每一層的擴展手段與極限，才不會把瓶頸猜錯。',
      example: { primary: '多 API 實例 + 一主多讀 PostgreSQL + Redis', alts: [] },
      keywords: ['nginx', 'PostgreSQL', 'Docker'],
      lab: null,
      points: [
        { b: 'API 無狀態', t: 'session 放 Redis、檔案放物件儲存、程序內不存跨請求資料——任何一台都能服務任何請求，前面放負載平衡器就能加台。' },
        { b: '資料庫先垂直', t: '加 CPU / 記憶體、調索引、加連線池——通常撐很久。別太早分散。' },
        { b: '讀寫分離', t: '寫主庫、讀副本。副本有延遲，「寫完立刻讀」要讀主庫（read-your-writes）。' },
        { b: '分片是最後手段', t: '依 tenant / user id 把資料拆到不同庫。跨分片 JOIN 與交易都很痛，非必要不做。' },
        { b: '瓶頸要量測', t: '壓測（k6、locust）找出第一個爆的地方；通常是 DB 連線或某條慢查詢，不是 CPU。' },
      ],
      checklist: [
        '能檢查自己的 API 是否無狀態、列出讓它有狀態的地方',
        '能畫出一主多讀的架構並說明延遲問題怎麼處理',
      ],
      refs: [],
    },
    {
      id: 'system-design',
      title: '系統設計思考框架',
      en: 'System design',
      level: 3,
      summary: '需求 → 估算 → API → 資料模型 → 架構 → 瓶頸與取捨，一個固定順序讓你面對新專案不慌。',
      why: '前面所有技能的組合題。有框架，設計會議就從「感覺」變成「因為 X 所以 Y」。',
      example: { primary: '固定的六步驟', alts: [] },
      keywords: [],
      lab: null,
      points: [
        { b: '1. 釐清需求', t: '功能性（誰做什麼）與非功能性（多少人、多快、多可靠、資料多大）。沒有數字的設計是猜。' },
        { b: '2. 粗估規模', t: 'DAU × 每人請求數 / 86400 = QPS；資料量 × 保留年數 = 儲存。數量級對就好。' },
        { b: '3. 定 API 與資料模型', t: '資源與端點、核心表與關係、哪些要索引。這一步用到領域 2 與 3 的全部。' },
        { b: '4. 畫高層架構', t: '客戶端 → CDN / LB → API → DB / 快取 / 佇列 / 物件儲存。先簡單，每個元件要能說出為什麼在那。' },
        { b: '5. 找瓶頸、加東西', t: '哪裡先爆？讀太多加快取與副本；寫太多加佇列；熱點要分散。每加一個元件就多一個要維運的東西。' },
        { b: '6. 講取捨', t: '一致性 vs 可用性、延遲 vs 成本、簡單 vs 彈性。設計沒有對錯，只有「在這個約束下的合理」。' },
      ],
      checklist: [
        '能用六步驟設計一個「短網址服務」或「通知系統」並說明每個取捨',
        '能對現有系統指出下一個會爆的瓶頸',
      ],
      refs: [
        { label: 'roadmap.sh：Backend Developer', url: 'https://roadmap.sh/backend' },
      ],
    },
  ],
}
