// 領域 8：演算法與系統設計
// 技能內文（points / checklist / refs）在 ./body/d8-algo.js，索引與內文的技能 id 一一對應（npm run validate 會檢查）
export default {
  id: 'algo',
  no: 8,
  title: '演算法與系統設計',
  en: 'ALGORITHMS & SYSTEM DESIGN',
  color: 'magenta',
  tagline: '後端的演算法不是刷題：是 Big-O 直覺、幾個真的會用到的結構與演算法，以及把它們組成系統的思考框架。',
  desc: '你不需要背紅黑樹，但要知道為什麼索引是 log n、迴圈裡打 query 是 n²、限流用 token bucket、快取用 LRU。這一區挑後端真的會遇到的部分，最後給一個系統設計的思考順序。',
  skills: [
    {
      id: 'big-o',
      title: 'Big-O 與後端常見複雜度',
      en: 'Big-O intuition',
      level: 1,
      summary: 'O(1)、O(log n)、O(n)、O(n log n)、O(n²) 分別對應 hash 查詢、索引、全表掃描、排序、巢狀迴圈 / N+1。',
      example: { primary: 'Python 內建結構 + SQL 查詢計畫', alts: [] },
      keywords: ['SQL', 'Python'],
      lab: 'BigOLab',
    },
    {
      id: 'data-structures',
      title: '後端常用資料結構',
      en: 'Data structures',
      level: 1,
      summary: 'hash map / set、陣列與佇列、堆（優先佇列）、樹（B-tree、trie）、圖——各自在後端哪裡出現。',
      example: { primary: 'Python collections + Redis 資料型別', alts: [] },
      keywords: ['Python'],
      lab: null,
    },
    {
      id: 'rate-limiting',
      title: '限流演算法',
      en: 'Rate limiting',
      level: 2,
      summary: 'token bucket 允許短暴衝、固定視窗有邊界問題、滑動視窗較平滑；用 Redis 實作跨實例共享。',
      example: { primary: 'Token bucket（Redis）', alts: ['nginx limit_req', 'API gateway 內建'] },
      keywords: ['nginx', 'OWASP'],
      lab: 'RateLimitLab',
    },
    {
      id: 'lru-cache',
      title: 'LRU 與快取淘汰',
      en: 'Cache eviction',
      level: 2,
      summary: '記憶體有限，快取滿了淘汰誰：LRU（最久沒用）最常見、LFU 看頻率、TTL 看時間。',
      example: { primary: 'LRU（functools.lru_cache、Redis allkeys-lru）', alts: ['LFU', 'FIFO', 'TTL-only'] },
      keywords: ['Python'],
      lab: null,
    },
    {
      id: 'queues-workers',
      title: '訊息佇列與背景工作',
      en: 'Queues & workers',
      level: 2,
      summary: '寄信、產報表、呼叫慢的第三方——丟進佇列讓 worker 做，API 立刻回；消費者要冪等。',
      example: { primary: 'Redis + RQ / Celery / arq', alts: ['RabbitMQ', 'Kafka（事件流）', '雲端佇列（SQS、Pub/Sub）'] },
      keywords: ['Python'],
      lab: null,
    },
    {
      id: 'scaling',
      title: '擴展：無狀態、負載平衡、讀寫分離',
      en: 'Scaling',
      level: 3,
      summary: 'API 無狀態就能水平擴展；資料庫先垂直、再讀寫分離、最後分片；快取與佇列吸收尖峰。',
      example: { primary: '多 API 實例 + 一主多讀 PostgreSQL + Redis', alts: [] },
      keywords: ['nginx', 'PostgreSQL', 'Docker'],
      lab: null,
    },
    {
      id: 'system-design',
      title: '系統設計思考框架',
      en: 'System design',
      level: 3,
      summary: '需求 → 估算 → API → 資料模型 → 架構 → 瓶頸與取捨，一個固定順序讓你面對新專案不慌。',
      example: { primary: '固定的六步驟', alts: [] },
      keywords: [],
      lab: null,
    },
  ],
}
